import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const rf = readFileSync(require.resolve("reactflow/dist/style.css"), "utf8");
const duru = readFileSync(new URL("../src/duru.css", import.meta.url), "utf8");
const css = (rf + "\n" + duru).replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
writeFileSync(new URL("../src/styles.ts", import.meta.url),
  "// GENERATED by scripts/gen-styles.mjs — do not edit\n" +
  "export const CSS = `" + css + "`;\n" +
  "let done = false;\n" +
  "export function injectStyles() {\n" +
  "  if (done) return; done = true;\n" +
  "  const el = document.createElement(\"style\");\n" +
  "  el.setAttribute(\"data-duru\", \"1\");\n" +
  "  el.textContent = CSS;\n" +
  "  document.head.appendChild(el);\n" +
  "}\n");
console.log("generated src/styles.ts (", css.length, "chars )");
